[project]
name = "ai_shell"
version = "0.2.0"
description = "A CLI tool that lets you ask an AI how to do things in Linux."
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "requests",
    "prompt_toolkit",
    "rich",
]

[project.scripts]
sam = "ai_shell.main:run_cli"
